version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
    timezone: Europe/Moscow
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.Net.Compilers
    versions:
    - 3.8.0
  - dependency-name: Newtonsoft.Json
    versions:
    - 12.0.3
